site_name: Librian中文文檔
nav:
- 主頁: 主頁.md
- 快速上手:
  - 第一次使用/安裝.md
  - 第一次使用/小試牛刀.md
- 製作galgame:
  - 用戶指南/起步.md
  - 用戶指南/劇本寫法.md
  - 用戶指南/劇本命令.md
  - 用戶指南/立繪.md
  - 用戶指南/鏡頭.md
  - 用戶指南/修改配置.md
  - 用戶指南/生成遊戲.md
- 進階:
  - 進階/前言.md
  - 進階/CSS與HTML.md
  - 進階/特效.md
  - 進階/嵌入代碼.md
  - 進階/其他技術.md
- 實現與原理: 
  - 原理/軟件結構.md
  - 原理/編譯.md
- 關於Librian: 
  - 關於Librian/關於Librian.md
  - 關於Librian/關於技術選型.md
  - 關於Librian/一些遺憾.md
  - 關於Librian/使用許可.md
theme:
    name: null
    custom_dir: 'material改'
    language: en
    palette:
    font:
      text: Roboto
      code: Roboto Mono
    logo:
      icon: "\uE80C"
    feature:
      tabs: false
extra_css:
  - '../pdf.css'
  - './樣式/css.css'
use_directory_urls: false
markdown_extensions:
    - attr_list
    - def_list
plugins:
    []
#   - pdf-export:
#       combined: True
#       combined_output_path: ./Librian文檔.pdf