site_name: Librian中文文檔
nav:
- 主頁: 主頁.md
- 第一次使用:
  - 第一次使用/安裝.md
- 製作galgame:
  - 用戶指南/起步.md
  - 用戶指南/劇本寫法.md
  - 用戶指南/劇本功能.md
  - 用戶指南/立繪.md
  - 用戶指南/客製化你的遊戲.md
  - 用戶指南/生成遊戲.md
- 進階:
  - 進階/前言.md
  - 進階/畫面的定製.md
  - 進階/特效.md
  - 進階/嵌入python.md
  - 進階/設計回想.md
- 一些遺憾: 接下來要做的/一些遺憾.md
- 關於Librian: 
  - 關於Librian/關於Librian.md
  - 關於Librian/關於實現.md
theme: material
extra_css:
  - '../pdf.css'
  - './樣式/css.css'
use_directory_urls: false
plugins:
  - pdf-export:
      combined: True
      combined_output_path: ./Librian文檔.pdf
      enabled_if_env: h